name: Formatting python code
on:
  workflow_dispatch:
  push:
   

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: autopep8
       uses: peter-evans/autopep8@v1
       with:
          args: --recursive --in-place --aggressive --aggressive .
     - name: Check for modified files
       id: git-check
       run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
     - name: echo
       run: echo ${{github.ref_name}}
     - name: Create Pull Request
       uses: gr2m/create-or-update-pull-request-action@v1
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
          title: "My pull request title"
          body: "My pull request body"
          branch: "my-pull-request-base-branch"
          commit-message: "My commit message for uncommitted changes in lib/ folder"
          labels: label1, label2
          team_reviewers: team1, team2
          update-pull-request-title-and-body: false
#        uses: peter-evans/create-pull-request@v3
#        with:
#           commit-message: autopep8 action fixes
#           title: Fixes by autopep8 action
#           body: This is an auto-generated PR with fixes by autopep8.
#           labels: autopep8, automated pr
#           branch: autopep8_patches
#           #base: autopep8_patches
          






