name: "Dags Deployment"
on:
  workflow_dispatch:
  push: 
    branches: [main, dags]
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash

env:
  S3_BUCKET:  data-engineering-airflow
  DAGS_PATH: dags/

    
permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2
  
jobs:
  main:
    strategy:
      matrix:
        environment: [dev, cert, prod]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Auth to PACCAR AWS
        uses: aws-actions/configure-aws-credentials@v1
        
        with:
          role-to-assume: arn:aws:iam::053342002484:role/github-oidc
          aws-region: us-east-1
 

      - name: Check for modified files
        id: git_check
        run: echo ::set-output name=modified::$(if git diff --stat HEAD -- .; then echo "true"; else echo "false";fi)
        working-directory:  "${{matrix.environment}}"

      - name: upload Dags to S3
        id: s3_upload
        if: steps.git_check.outputs.modified == 'true'    
        run: aws s3 sync . "s3://${{env.S3_BUCKET}}-${{matrix.environment}}/${{env.DAGS_PATH}}"
        working-directory:  "${{matrix.environment}}"
