name: Formatting python code
on:
  workflow_dispatch:
  push:
   

jobs:
  pep8:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: autopep8
       uses: peter-evans/autopep8@v1
       with:
          args: --recursive --in-place --aggressive --aggressive .
     - name: Check for modified files
       id: git-check
       run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
     - name: echo
       run: echo ${{github.ref_name}}
     - name: Create Pull Request
       uses: devops-infra/action-pull-request@v0.4.2
       with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: pep8
        target_branch: master
        title: My pull request
        template: .github/PULL_REQUEST_TEMPLATE.md
        body: "**Automated pull request**"
        label: enhancement
        draft: true
        old_string: "<!-- Add your description here -->"
        new_string: "** Automatic pull request**"
        get_diff: true
        ignore_users: "dependabot"
#        uses: peter-evans/create-pull-request@v3
#        with:
#           commit-message: autopep8 action fixes
#           title: Fixes by autopep8 action
#           body: This is an auto-generated PR with fixes by autopep8.
#           labels: autopep8, automated pr
#           branch: autopep8_patches
#           #base: autopep8_patches
          






