name: "Dags Deployment"
on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]
defaults:
  run:
    shell: bash

env:
  ENVIRONMENT: test
    
permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2
  
jobs:
  terraform:
    name:   "terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Auth to PACCAR AWS
        uses: aws-actions/configure-aws-credentials@v1
        
        with:
          role-to-assume: arn:aws:iam::053342002484:role/github-oidc
          aws-region: us-east-1
 

      - uses: actions/checkout@v2
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
